services:
  magnet-to-strm:
    image: ghcr.io/zmhawk/magnet-to-strm:latest
    env_file:
      - .env
    ports:
      - "7000:8080"
    volumes:
      - ./data:/data
      - ./config.toml:/etc/magnet-to-strm/config.toml:ro

  rclone:
    image: rclone/rclone:latest
    ports:
      - "7001:8080"
    volumes:
      - ./rclone.conf:/config/rclone/rclone.conf:ro
    command:
      - serve
      - http
      - "magnet:"
      - --addr=:8080
      - --read-only
      - --server-write-timeout=24h
      - --buffer-size=1G
