# 网盘中原有的收藏资源
[openlist]
type = webdav
url = https://openlist.home.arpa/dav
vendor = other
user = your_username
pass = your_password, 使用 rclone obscure 生成

# 磁链管理的资源
[magnet]
type = webdav
url = http://mts.home.arpa:7000/dav
vendor = other

[combine]
type = combine
upstreams = 网盘=openlist: 磁链=magnet: